language: java
jdk:
  - oraclejdk8
  - oraclejdk7
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn versioneye:update
  - mvn clean cobertura:cobertura coveralls:report

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "sNNTtfXXQAFOlmgjZXRLwtKVguLkHlcJyGkwWbQ9rYvy30kx0KjZSV44nvNMgdlBWcr5wJiS4BacQ8x7IJEYe8VLONLXuKEHMlS6KXYn9SaLImsBTgfPuK2Pmt7snwKALjOLmewBIM/PNtWtqCR56N10w2e+6ZYc/cZMfd4mhGOmilqPK+iF6Pkn9sVCXKtLOACVUp2n0p4agXWhIfOFC3Yj6YOeiaCH3k67Z9To1S7SUaucmvkAwbGhwkXjjmvDICcyqPMw3xZN+SpDdzOAc/viRpBhXXb0/k+ZaQ8UM3bePmGRN+gbP7m+8Os79lbcQ4I1vSJTxTSLOGsfyxiwQTBE+OMsK1mpSR7e+urspgO7Q9YaneD5vQuC61Nv7Xnb5gKGNaRCrqYxBn5ZyTU5gt4fbPuNibGMlsIE1gmn8bosL1z82pFMJ1W8/30uZrFzTI2g+MoX9k9930c/oL2CO28TxxzxVDSGSrz1a66qvEPOQr9UG+D5+mV0xwnhugoLxhj8sXeZPDNS1HtqpjQ/GT2PCRKWpUqH4yeq8ZgvlUW5rK6aAFU3E+K6lpajcnZxUMsf9JixYeFTcgXQf2zCYu2J/DjmWsRUKkg4qbIoOyz+DvttZrDYlJT0eWk8mFUs4bOsEXSRYD/QubOzWJxwt6Jjma5q+bmu9Y/3LGNXV1U="
addons:
  coverity_scan:
    project:
      name: "Iurii-Dziuban/kotlin-examples"
      description: "Build submitted via Travis CI"
    notification_email: ydzyuban@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn compile -DskipTests"
    branch_pattern: master